employee_mangement_system/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.views.static import serve
from django.conf import settings
from app01.views import dept, user, pretty, admin, account, task, order, chart, upload, city, fenzhang

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),
    # 部门管理
    path('dept/list', dept.dept_list),
    path('dept/add', dept.dept_add),
    path('dept/delete', dept.dept_delete),
    path('dept/<int:nid>/edit', dept.dept_edit),
    path('dept/multi', dept.dept_multi),

    # 用户管理
    path('user/list', user.user_list),
    path('user/add', user.user_add),
    path('user/<int:nid>/edit', user.user_edit),
    path('user/delete', user.user_delete),

    # 靓号管理
    path('pretty/list', pretty.pretty_list),
    path('pretty/add', pretty.pretty_add),
    path('pretty/<int:nid>/edit', pretty.pretty_edit),
    path('pretty/delete', pretty.pretty_delete),

    # 管理员管理
    path('admin/list', admin.admin_list),
    path('admin/add', admin.admin_add),
    path('admin/<int:nid>/edit', admin.admin_edit),
    path('admin/delete', admin.admin_delete),
    path('admin/<int:nid>/reset', admin.admin_reset),

    # 登录
    path('login', account.login),
    path('logout', account.logout),
    path('image/code', account.image_code),

    # 任务管理
    path('task/list', task.task_list),
    path('task/add', task.task_add),

    # 订单管理
    path('order/list', order.order_list),
    path('order/add', order.order_add),
    path('order/<int:nid>/delete', order.order_delete),
    path('order/detail', order.order_detail),
    path('order/<int:nid>/edit', order.order_edit),

    # 图表
    path('chart/list', chart.chart_list),
    path('chart/bar', chart.chart_bar),
    path('chart/pie', chart.chart_pie),
    path('chart/line', chart.chart_line),

    # 上传
    path('upload/form', upload.upload_form),
    path('upload/modal/form', upload.upload_modal_form),

    # 城市管理
    path('city/list', city.city_list),

    # 分账管理
    path('fenzhang/compute', fenzhang.compute),
    path('fenzhang/create', fenzhang.create),
    path('fenzhang/<int:nid>/modify', fenzhang.modify),

]

app01/models.py
from django.db import models


# Create your models here.
class Admin(models.Model):
    """  管理员  """
    username = models.CharField(verbose_name="用户名", max_length=32)
    password = models.CharField(verbose_name="密码",max_length=64)

    def __str__(self):
        return self.username


class Department(models.Model):
    """ 部门表 """
    title = models.CharField(max_length=32,verbose_name='标题') # verbose_name 字段注释

    def __str__(self):
        return self.title


class UserInfo(models.Model):
    """ 员工 """
    name = models.CharField(verbose_name='姓名', max_length=16)
    password = models.CharField(verbose_name='密码', max_length=64)
    age = models.CharField(verbose_name='年龄', max_length=2)
    account = models.DecimalField(verbose_name='账户余额', max_digits=10, decimal_places=2, default=0)

    create_time = models.DateTimeField(verbose_name='入职时间')

    #无约束
    # dept_id = models.BigIntegerField(verbose_name='部门ID')

    #外键约束
    # - to,与那张表关联
    # - to_field,与表里的那一列关联
    # 注意：django自动会给dept在生成到mysql数据库中时变成dept_id
    # on_delete=models.SET_NULL 当部门删除时，员工部门列置空
    dept = models.ForeignKey(verbose_name="部门",to="Department", to_field="id", null=True, blank=True, on_delete=models.SET_NULL)

    # 从Django层面限制gender 1是男，2是女，只能是这两值
    gender_choices = (
        (1, '男'),
        (2, '女')
    )
    gender = models.SmallIntegerField(verbose_name='性别', choices=gender_choices)


class PrettyNum(models.Model):
    """ 靓号表 """
    # 设置默认空值 null=True,blank=True
    mobile = models.CharField(verbose_name='手机号', max_length=11)
    price = models.IntegerField(verbose_name='价格', default=0)

    lever_choice=(
        (1,'1级'),
        (2,'2级'),
        (3,'3级'),
        (4,'4级'),
    )
    lever = models.SmallIntegerField(verbose_name="级别",choices=lever_choice,default=1)

    status_choices = (
        (1, '已占用'),
        (2, '未使用'),
    )
    status = models.SmallIntegerField(verbose_name="状态",choices=status_choices,default=2)


class Task(models.Model):
    """ 任务 """
    lever_choices = (
        (1, '紧急'),
        (2, '重要'),
        (3, '临时')
    )
    level = models.SmallIntegerField(verbose_name='级别', choices=lever_choices, default=1)
    title = models.CharField(verbose_name='标题', max_length=64)
    detail = models.TextField(verbose_name='详细信息')
    user = models.ForeignKey(verbose_name='负责人',to='Admin', to_field='id', on_delete=models.CASCADE)


class Order(models.Model):
    """ 订单 """
    oid = models.CharField(verbose_name="订单号", max_length=64)
    title = models.CharField(verbose_name="名称", max_length=32)
    price = models.IntegerField(verbose_name="价格", default=0)

    status_choices = (
        (1, "待支付"),
        (2, "已支付")
    )

    status = models.SmallIntegerField(verbose_name="状态", choices=status_choices, default=1)
    admin = models.ForeignKey(verbose_name="管理员", to="Admin", on_delete=models.CASCADE)


class Boss(models.Model):
    """ 老板 """
    name = models.CharField(verbose_name="姓名", max_length=32)
    age = models.IntegerField(verbose_name="年龄")
    img = models.CharField(verbose_name="头像", max_length=128)


class City(models.Model):
    """ 城市 """
    name = models.CharField(verbose_name="城市", max_length=32)
    count = models.IntegerField(verbose_name="人口")
    # FileField本质上数据库也是CharField，自动保存数据(使用upload_to自动上传到media目录家下的city文件夹里)
    img = models.FileField(verbose_name="LOGO", max_length=128, upload_to='city')

class FenZhang(models.Model):
    """ 分账 """
    name = models.CharField(verbose_name="用户名字", max_length=32)
    count = models.IntegerField(verbose_name="数量")
    huafei = models.IntegerField(verbose_name="花费")
    shoukuan = models.IntegerField(verbose_name="收款")
    owner = models.CharField(verbose_name="拥有者", max_length=128, null=True, blank=True,)

app01/views/account.py
# author Amelia
# 2023/8/7 21:06
from app01 import models
from django.shortcuts import render,redirect, HttpResponse
from django import forms
from io import BytesIO
from app01.utils.encrypt import md5
from app01.utils.code import check_code

class LoginForm(forms.Form):
    username = forms.CharField(
        label='用户名',
        widget=forms.TextInput(attrs={"class":"form-control"}),required=True
    )
    password = forms.CharField(
        label='密码',
        widget=forms.PasswordInput(attrs={"class":"form-control"}),required=True
    )

    code = forms.CharField(
        label='验证码',
        widget=forms.TextInput(attrs={"class":"form-control"}),required=True
    )

    def clean_password(self):
        pwd = self.cleaned_data.get("password")
        return md5(pwd)

def login(request):
    """ 登录 """
    if request.method=='GET':
        form = LoginForm()
        return render(request, 'login.html',{'form':form})

    form = LoginForm(data=request.POST)
    if form.is_valid():
        # 验证成功，获取到的用户名和密码
        # {'username',:'123', 'password':'123'}
        # print(form.cleaned_date)
        user_input_code = form.cleaned_data.pop('code')
        code = request.session.get('image_code', "")
        if code.lower() != user_input_code:
            form.add_error("code","验证码错误")
            return render(request, 'login.html', {'form': form})

        # 去数据库校验用户和密码是否正确
        admin_object = models.Admin.objects.filter(**form.cleaned_data).first()
        if not admin_object:
            form.add_error('password', "用户名或密码错误")
            return render(request, 'login.html', {'form': form})

        # 用户名密码正确
        # 网站生成随机字符串；写到用户浏览器的coolie中，在写入session中
        request.session["info"] = {'id': admin_object.id, 'name': admin_object.username}
        # session设置7天失效
        request.session.set_expiry(60*60*24*7)
        return redirect('/admin/list')

    return render(request, 'login.html', {'form': form})

def logout(request):
    """ 注销 """
    request.session.clear()

    return redirect('/login')

def image_code(request):
    """ 生成图片验证码 """
    # 调用pillow函数，生成图片
    img, code_string = check_code()

    # 写入到自己的session中（以便于后续获取验证码再进行校验）
    request.session['image_code'] = code_string
    # 给session设置60s后超时
    request.session.set_expiry(60)

    stream = BytesIO()
    img.save(stream, 'png')

    return HttpResponse(stream.getvalue())

app01/views/admin.py
# author Amelia
# 2023/8/7 15:37
from app01 import models
from django.shortcuts import render,redirect
from app01.utils.Pagination import Pagination
from app01.utils.form import AdminModelForm, AdminEditModelForm, AdminResetModelForm

def admin_list(request):
    data_dict = {}
    search_data = request.GET.get("q","") # 如果没有q，则赋值""
    if search_data:
        data_dict = {"mobile__contains":search_data}

    queryset = models.Admin.objects.filter(**data_dict)

    page_object = Pagination(request, queryset)

    context = {
        'queryset': page_object.page_queryset,  # 分完页后的数据
        "search_data": search_data,
        "page_string": page_object.html()  # 页码信息
    }
    return render(request,'admin_list.html',context)


def admin_add(request):
    title = "新建管理员"

    if request.method=='GET':
        form = AdminModelForm()
        return render(request, 'change.html', {'title': title,'form':form})

    # POST提交，数据校验
    form = AdminModelForm(data=request.POST)
    if form.is_valid():
        # 如果数据合法，保存到数据库
        form.save()
        return redirect('/admin/list')

    return render(request, 'change.html', {'form': form})


def admin_edit(request,nid):
    title = "编辑管理员"
    row_obj = models.Admin.objects.filter(id=nid).first()

    if not row_obj:
        return redirect('/admin/list')

    if request.method=='GET':
        form = AdminEditModelForm(instance=row_obj)
        return render(request, 'change.html',{'title': title,'form':form})

    # POST提交，数据校验
    form = AdminEditModelForm(data=request.POST, instance=row_obj)
    if form.is_valid():
        # 如果想要在用户输入以外，增加其他字段赋值
        # form.instance.字段名 = 值
        # 如果数据合法，保存到数据库
        form.save()
        return redirect('/admin/list')
    else:
        return render(request, 'change.html', {'title': title,'form':form} )


def admin_delete(request):
    nid = request.GET.get('nid')
    models.Admin.objects.filter(id=nid).delete()
    return redirect('/admin/list')


def admin_reset(request,nid):
    """ 重置密码 """
    row_obj = models.Admin.objects.filter(id=nid).first()

    title = "重置密码 - {}".format(row_obj.username)
    if not row_obj:
        return redirect('/admin/list')

    if request.method=='GET':
        form = AdminResetModelForm()
        return render(request, 'change.html',{'title': title,'form':form})

    # POST提交，数据校验
    form = AdminResetModelForm(data=request.POST, instance=row_obj)
    if form.is_valid():
        form.save()
        return redirect('/admin/list')
    else:
        return render(request, 'change.html', {'title': title,'form':form} )

app01/views/chart.py
# author Amelia
# 2023/8/11 18:51
from django.shortcuts import render
from django.http import JsonResponse


def chart_list(request):
    """数据统计页面"""
    return render(request,'chart_list.html')

def chart_bar(request):
    """ 构造柱状图数据 """
    legend = ["梁吉宁"]
    series_list = [
              {
                "name": '销量',
                "type": 'bar',
                "data": [5, 20, 36, 10, 10, 20]
              }
            ]
    x_axis = ["1月","2月","3月","4月","5月","6月"]

    result = {
        "status": True,
        "data":{
            'legend': legend,
            "series": series_list,
            "xAxis": x_axis
        }
    }

    return JsonResponse(result)


def chart_pie(request):
    """ 构造饼状图数据 """
    series_list = [{"value": 1048, "name": 'IT部门'},
                    {"value": 735, "name": '运营'},
                    {"value": 580, "name": '新媒体'},
                    {"value": 484, "name": '销售'},
                    {"value": 300, "name": '商务'}]

    result = {
        "status": True,
        "data":{
            "series": series_list,
        }
    }

    return JsonResponse(result)


def chart_line(request):
    """ 构造折线图数据 """
    legend = ['Email', 'Union Ads', 'Video Ads', 'Direct', 'Search Engine']
    series_list = [
                {
                  "name": 'Email',
                  "type": 'line',
                  "stack": 'Total',
                  "data": [120, 132, 101, 134, 90, 230, 210]
                },
                {
                  "name": 'Union Ads',
                  "type": 'line',
                  "stack": 'Total',
                  "data": [220, 182, 191, 234, 290, 330, 310]
                },
                {
                  "name": 'Video Ads',
                  "type": 'line',
                  "stack": 'Total',
                  "data": [150, 232, 201, 154, 190, 330, 410]
                },
                {
                  "name": 'Direct',
                  "type": 'line',
                  "stack": 'Total',
                  "data": [320, 332, 301, 334, 390, 330, 320]
                },
                {
                  "name": 'Search Engine',
                  "type": 'line',
                  "stack": 'Total',
                  "data": [820, 932, 901, 934, 1290, 1330, 1320]
                }
            ]
    x_axis = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']

    result = {
        "status": True,
        "data":{
            'legend': legend,
            "series": series_list,
            "xAxis": x_axis
        }
    }

    return JsonResponse(result)

app01/views/city.py
# author Amelia
# 2023/8/14 15:49
from django.shortcuts import render,redirect,HttpResponse
from app01 import models

def city_list(request):
    """ 部门列表 """
    # 去数据库获取部门列表
    queryset = models.City.objects.all()
    return render(request,'city_list.html',{'queryset': queryset})

app01/views/dept.py
# author Amelia
# 2023/8/7 15:09
import os
from openpyxl import load_workbook
from django.shortcuts import render,redirect,HttpResponse
from app01 import models

def dept_list(request):
    """ 部门列表 """
    # 去数据库获取部门列表
    queryset = models.Department.objects.all()
    return render(request,'dept_list.html',{'queryset': queryset})

def dept_add(request):
    """ 添加部门 """
    if request.method=='GET':
        return render(request, 'dept_add.html')
    else:
        title = request.POST.get("title")
        models.Department.objects.create(title=title)
        return redirect('/dept/list')

def dept_delete(request):
    """ 删除 """
    nid = request.GET.get('nid')
    models.Department.objects.filter(id=nid).delete()
    return redirect('/dept/list')

def dept_edit(request,nid):
    """ 修改部门 """
    if request.method=='GET':
        row_obj = models.Department.objects.get(id=nid)
        return render(request, 'dept_edit.html',{'obj': row_obj})
    else:
        title = request.POST.get("title")
        models.Department.objects.filter(id=nid).update(title=title)
        return redirect('/dept/list')


def dept_multi(request):
    """ 批量删除 """
    # 1.获取用户上传的文件对象
    file_object = request.FILES.get("exc")

    # 2.对象传递给openpyxl,由openpyxl读取文件的内容
    wb = load_workbook(file_object)
    sheet = wb.worksheets[0]

    # 3.循环获取每一行数据
    for row in sheet.iter_rows(min_row=2):
        print(row)
        text = row[0].value
        exists = models.Department.objects.filter(title=text).exists()
        if not exists:
            models.Department.objects.create(title=text)

    return redirect('/dept/list')

app01/views/pretty.py
# author Amelia
# 2023/8/7 15:09
from django.shortcuts import render,redirect
from app01 import models
from app01.utils.Pagination import Pagination
from app01.utils.form import PrettyModelForm, PrettyEditModelForm


""" 当编辑和新增字段个数不一样，或者属性不一样时，可以单独个编辑的Form """
def pretty_list(request):

    # 多条件查询
    data_dict = {}
    search_data = request.GET.get("q","") # 如果没有q，则赋值""
    if search_data:
        data_dict = {"mobile__contains":search_data}

    # 根据用户想要访问的页码，计算出起止位置
    queryset = models.PrettyNum.objects.filter(**data_dict).order_by("-lever")

    page_object = Pagination(request,queryset)

    context = {
        'queryset': page_object.page_queryset, # 分完页后的数据
        "search_data": search_data,
        "page_string": page_object.html() # 页码信息
    }

    return render(request,'pretty_list.html',context)

def pretty_add(request):
    if request.method=='GET':
        form = PrettyModelForm()
        return render(request, 'pretty_add.html', {'form': form})
    else:
        # POST提交，数据校验
        form = PrettyModelForm(data=request.POST)
        if form.is_valid():
            # 如果数据合法，保存到数据库
            form.save()
            return redirect('/pretty/list')
        else:
            return render(request, 'pretty_add.html', {'form': form})

def pretty_edit(request,nid):
    row_obj = models.PrettyNum.objects.filter(id=nid).first()
    if request.method=='GET':
        form = PrettyEditModelForm(instance=row_obj)
        return render(request, 'pretty_edit.html',{'form': form})

    # POST提交，数据校验
    form = PrettyEditModelForm(data=request.POST, instance=row_obj)
    if form.is_valid():
        # 如果想要在用户输入以外，增加其他字段赋值
        # form.instance.字段名 = 值
        # 如果数据合法，保存到数据库
        form.save()
        return redirect('/pretty/list')
    else:
        return render(request, 'pretty_edit.html', {'form': form})

def pretty_delete(request):
    nid = request.GET.get('nid')
    models.PrettyNum.objects.filter(id=nid).delete()
    return redirect('/pretty/list')

app01/templates/order_list.html
{% extends 'layout.html' %}

{% block content %}
    <div >
        <input id="btnAdd" type="button" value="新建订单" class="btn btn-success" style="margin-bottom: 10px"/>

        <div class="panel panel-default">
          <!-- Default panel contents -->
          <div class="panel-heading">订单列表</div>

          <!-- Table -->
          <table class="table">
            <thead>
              <tr>
                <th>ID</th>
                <th>订单号</th>
                <th>名称</th>
                <th>价格</th>
                <th>状态</th>
                <th>管理员</th>
                <th>操作</th>
              </tr>
            </thead>
            <tbody>
            {% for foo in queryset %}
              <tr uid="{{ foo.id }}">
                <td>{{ foo.id }}</td>
                <td>{{ foo.oid }}</td>
                <td>{{ foo.title }}</td>
                <td>{{ foo.price }}</td>
                <td>{{ foo.get_status_display }}</td>
                <td>{{ foo.get_admin_display }}</td>
                <td>
{#                    <a class="btn btn-primary btn-xs" href="/order/{{ foo.id }}/edit">编辑</a>#}

                    <input uid="{{ foo.id }}" class="btn btn-primary btn-xs btn-edit" type="button" value="编辑" />
{#                    <a class="btn btn-danger btn-xs" href="/order/delete?nid={{ foo.id }}">删除</a>#}
                    <input uid="{{ foo.id }}" class="btn btn-danger btn-xs btn-delete" type="button" value="删除" />
                </td>
              </tr>
            {% endfor %}

            </tbody>
          </table>

        </div>
        <nav aria-label="Page navigation">
              <ul class="pagination">
                {{ page_string }}
              </ul>

        </nav>
    </div>

    <!-- 新建/编辑 订单对话框 -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">新建</h4>
          </div>
          <div class="modal-body">
             <form id="formAdd">
                {% for filed in form %}
                    <div class="form-group" style="position: relative;margin-bottom: 20px">
                        <label>{{ filed.label }}</label>
                        {{ filed }}
                        <span class="err-msg" style="color: red;position:absolute;"></span>
                    </div>

                {% endfor %}

             </form>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
            <button type="button" class="btn btn-primary" id="btnSave">保存</button>
          </div>
        </div>
      </div>
    </div>


    <!-- 删除订单对话框 -->
    <div class="modal fade" id="delModal" tabindex="-1" role="dialog" aria-labelledby="delModalLabel">
      <div class="modal-dialog" role="document"  style="width: 35%">
            <div class="alert alert-danger alert-dismissible fade in" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
              <h4>是否确定删除？</h4>
              <p style="margin: 10px 0;">删除后，所有关联的相关数据都会被删除。</p>
              <p style="text-align: right">
                <button id="btnConfirmDelete" type="button" class="btn btn-danger" data-dismiss="modal">确 定</button>
                <button type="button" class="btn btn-default">取 消</button>
              </p>
            </div>
      </div>
    </div>

{% endblock %}

{% block js %}
    <script type="text/javascript">
        var DELETE_ID = 0
        let EDIT_ID = 0
        $(function (){
            bindBtnAddEvent();
            bindBtnSaveEvent();
            bindBtnDeleteEvent();
            bindBtnConfirmDeleteEvent();
            bindBtnEditEvent();
        })
        function bindBtnAddEvent(){
            $('#btnAdd').click(function (){
                EDIT_ID = undefined

                // 清空对话框中的数据
                $("#formAdd")[0].reset();

                $('#myModalLabel').text("新建");
                // 点击新建按钮，显示对话框
                $('#myModal').modal('show');
            })
        }

        function bindBtnSaveEvent(){
            $('#btnSave').click(function (){
                // 清除错误信息
                $('.err-msg').empty()

                if(EDIT_ID){
                    doEdit();
                }else{
                    doAdd();
                }


            })
        }

        function doAdd(){
             $.ajax({
                    url: "/order/add",
                    type: "post",
                    data: $("#formAdd").serialize(),
                    success:function (res){
                        console.log(res)
                        if(res.status){
                            {#alert('创建成功')#}
                            // 清空表单 $('#formAdd')是jqeury对象->$('#formAdd')[0] DOM对象
                            $('#formAdd')[0].reset();
                            $('#myModel').modal('hide');
                            //刷新页面
                            location.reload();
                        }else{
                            $.each(res.error, function (name, errorList){
                                $('#id_'+name).next().text(errorList[0])
                            })
                        }
                    }
                })
        }
        function doEdit(){
             $.ajax({
                    url: "/order/"+EDIT_ID+"/edit",
                    type: "post",
                    data: $("#formAdd").serialize(),
                    success:function (res){
                        console.log(res)
                        if(res.status){
                            {#alert('编辑成功')#}
                            // 清空表单 $('#formAdd')是jqeury对象->$('#formAdd')[0] DOM对象
                            $('#formAdd')[0].reset();
                            $('#myModel').modal('hide');
                            //刷新页面
                            location.reload();
                        }else{
                            if(res.msg){
                                alert(msg)
                            }else{
                                $.each(res.error, function (name, errorList){
                                    $('#id_'+name).next().text(errorList[0])
                                })
                            }
                        }
                    }
                })
        }

        function bindBtnDeleteEvent(){
            $('.btn-delete').click(function (){
                // 点击删除按钮，显示删除对话框
                $('#delModal').modal('show');

                //获取当前行的ID并赋值给全部变量
                DELETE_ID = $(this).attr("uid")
                console.log(DELETE_ID)
            })
        }

        function bindBtnConfirmDeleteEvent(){
            $('#btnConfirmDelete').click(function (){
                $.ajax({
                    url: "/order/"+DELETE_ID+"/delete",
                    type: "GET",
                    dataType: "JSON",
                    success: function (res){
                        if(res.status){
                            {#alert("删除成功")#}
                            $('#delModal').modal('hide');
                            //在页面上当前一行得删除
                            {#$("tr[uid='"+DELETE_ID+"']").remove();#}
                            //要删除的ID置空
                            DELETE_ID = 0;
                            location.reload();
                        }else{
                            alert(res.error);
                        }
                    }
                })
            })
        }

        function bindBtnEditEvent(){
            $('.btn-edit').click(function (){
                // 清空对话框中的数据
                $("#formAdd")[0].reset();

                let uid = $(this).attr("uid")
                EDIT_ID = uid

                $.ajax({
                    url: '/order/detail',
                    type: 'GET',
                    data:{
                        uid: uid
                    },
                    dataType: 'JSON',
                    success: function (res){
                        console.log(res)
                        if(res.status){
                            $.each(res.data, function (name, value){
                                $("#id_"+name).val(value)
                            })
                            // 修改对话框标题
                            $('#myModalLabel').text("编辑")
                            // 点击新建按钮，显示对话框
                            $('#myModal').modal('show');
                        }else{
                            alert(res.error);
                        }
                    }


                })
            })
        }
    </script>
{% endblock %}

app01/templates/user_add.html
{% extends 'layout.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css' %}">
{% endblock %}

{% block content %}
    <div class="panel panel-default" style="margin-left: 10%; margin-right: 10%;">
    <div class="panel-heading">
    <h3 class="panel-title">新建用户</h3>
  </div>
  <div class="panel-body">
    <form method="post">
        {% csrf_token %}

        {% for filed in form %}
            <div class="form-group">
                <label>{{ filed.label }}</label>
                {{ filed }}
                <span style="color: red">{{ filed.errors.0 }}</span>
            </div>

        {% endfor %}

        <button type="submit" class="btn btn-primary">确定</button>
    </form>
  </div>
</div>

{% endblock %}

{% block js %}
    <script type="text/javascript" href="{% static 'plugins/bootstrap-datepicker/js/bootstrap-datepicker.js'%} "></script>
    <script type="text/javascript" href="{% static 'plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js'%} "></script>
    <script>
        $(function (){
            $('#id_create_time').datepicker({
                format: 'yyyy-mm-dd',
                startDate: '0',
                language: "zh-CN",
                autoclose: true
            })
        })
    </script>
{% endblock %}

app01/templates/user_list.html
{% extends 'layout.html' %}

{% block content %}
    <div style="margin-bottom: 10px">
        <a class="btn btn-success" href="/user/add" ><span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>新建用户</a>
    </div>
    <div class="panel panel-default">
      <!-- Default panel contents -->
      <div class="panel-heading">用户列表</div>

      <!-- Table -->
      <table class="table">
        <thead>
          <tr>
            <th>ID</th>
            <th>姓名</th>
            <th>密码</th>
            <th>年龄</th>
            <th>余额</th>
            <th>入职时间</th>
            <th>性别</th>
            <th>所属部门</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
        {% for foo in queryset %}
          <tr>
            <td>{{ foo.id }}</td>
            <td>{{ foo.name }}</td>
            <td>{{ foo.password }}</td>
            <td>{{ foo.age }}</td>
            <td>{{ foo.account }}</td>
            <td>{{ foo.create_time|date:'y-m-d H:i:s' }}</td>
            <td>{{ foo.get_gender_display }}</td>
            <td>{{ foo.dept.title }}</td>
            <td>
                <a class="btn btn-primary btn-xs" href="/user/{{ foo.id }}/edit">编辑</a>
                <a class="btn btn-danger btn-xs" href="/user/delete?nid={{ foo.id }}">删除</a>
            </td>
          </tr>
        {% endfor %}

        </tbody>
      </table>
    </div>
    </div>
{% endblock %}